In [1]:
import numpy as np

In [ ]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

vector1 = np.array([1,2,3,4,5,6,7,8,9,10])
vector1

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

zeros = np.zeros((3, 3), dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

matrix3 = np.random.randint(1, 11, size=(5, 5))  
print(matrix3)

[[ 2 10  8  1  9]
 [ 3  4  4  9  5]
 [ 8  5  6  8  3]
 [ 9  2  8  9  2]
 [ 5  4 10  3  5]]


In [5]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

matrix4 = np.random.rand(4, 4)
print(matrix4)

[[0.84256137 0.37261267 0.33861396 0.76991978]
 [0.87179766 0.38842955 0.77834614 0.12590704]
 [0.15663129 0.53705346 0.60036838 0.82400437]
 [0.5903268  0.63809357 0.1704145  0.74101857]]


In [6]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
# та виконайте на них поелементні операції додавання, віднімання та множення.

vector5_1 = np.random.randint(1, 11, size=5)
vector5_2 = np.random.randint(1, 11, size=5)
print(vector5_1)
print(vector5_2)
print(vector5_1 + vector5_2)
print(vector5_1 - vector5_2)
print(vector5_1 * vector5_2)

[8 7 2 1 9]
[1 8 8 9 4]
[ 9 15 10 10 13]
[ 7 -1 -6 -8  5]
[ 8 56 16  9 36]


In [7]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

vector6_1 = np.random.randint(1, 11, size=7)
vector6_2 = np.random.randint(1, 11, size=7)
print(vector6_1)
print(vector6_2)
print(np.dot(vector6_1, vector6_2))

[6 9 6 2 9 5 8]
[10  5  3  7  7  3  1]
223


In [8]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix7_1 = np.random.randint(1, 11, size=(2, 2)) 
matrix7_2 = np.random.randint(1, 11, size=(2, 3)) 
print(matrix7_1)
print(matrix7_2)
print(np.dot(matrix7_1, matrix7_2))

[[3 6]
 [2 6]]
[[5 4 3]
 [2 7 1]]
[[27 54 15]
 [22 50 12]]


In [9]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix8 = np.random.randint(1, 11, size=(3, 3)) 
print(matrix8)
inv1 = np.linalg.inv(matrix8)
print(inv1)

[[ 2  5 10]
 [ 9  6  3]
 [10  9  7]]
[[ 0.2         0.73333333 -0.6       ]
 [-0.44       -1.14666667  1.12      ]
 [ 0.28        0.42666667 -0.44      ]]


In [10]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix9 = np.random.rand(4, 4)
print(matrix9)
inv2 = np.linalg.inv(matrix9)
print(inv2)

[[0.9237445  0.44473454 0.6929727  0.48968569]
 [0.76946969 0.59250703 0.90151228 0.77976741]
 [0.32499101 0.91539784 0.47504189 0.15030291]
 [0.08423072 0.46015591 0.68338195 0.64695293]]
[[ -1.64554657   3.6032373    0.02744011  -3.10379725]
 [ -6.05530153   7.05152508   1.62872758  -4.29421881]
 [ 17.06818789 -21.50533454  -1.02820039  13.23999437]
 [-13.50809744  17.23162967  -0.07593493  -8.98137671]]


In [11]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами 
# в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix10 = np.random.randint(1, 11, size=(3, 4)) 
vector10 = np.random.randint(1, 11, size=4)
print(matrix10)
print(vector10)
print(np.dot(matrix10, vector10))

[[ 8  5  5 10]
 [ 5  8  6 10]
 [ 6  7  3  4]]
[2 8 8 5]
[146 172 112]


In [12]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами 
# в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix11 = np.random.rand(2, 3)
vector11 = np.random.rand(3)
print(matrix11)
print(vector11)
print(np.dot(matrix11, vector11))

[[0.6924777  0.98892141 0.47969279]
 [0.84733556 0.44434822 0.19226538]]
[0.21591618 0.87531315 0.55649311]
[1.28207879 0.67889165]


In [13]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
# та виконайте їхнє поелементне множення.

matrix12_1 = np.random.randint(1, 11, size=(2, 2))
matrix12_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix12_1)
print(matrix12_2)
print(matrix12_1 * matrix12_2)

[[ 7 10]
 [ 3  2]]
[[3 5]
 [8 3]]
[[21 50]
 [24  6]]


In [14]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

matrix13_1 = np.random.randint(1, 11, size=(2, 2))
matrix13_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix13_1)
print(matrix13_2)
print(matrix13_1 + matrix13_2)

[[7 2]
 [2 2]]
[[8 9]
 [7 8]]
[[15 11]
 [ 9 10]]


In [15]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix14 = np.random.randint(1, 101, size=(5, 5))
print(matrix14)
print(matrix14.sum())

[[59 44 14  7 47]
 [97 87  8 55 86]
 [27 13 36 40 77]
 [21 79 61 31  4]
 [68 72 10  9 41]]
1093


In [16]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix15_1 = np.random.randint(1, 11, size=(4, 4))
matrix15_2 = np.random.randint(1, 11, size=(4, 4))
print(matrix15_1)
print(matrix15_2)
print(matrix15_1 - matrix15_2)

[[ 4 10  3  3]
 [ 5  3  5  8]
 [ 8  1  5  7]
 [ 6 10 10  5]]
[[ 1  2  7  1]
 [ 9  4  5 10]
 [ 7  1  4  7]
 [ 9  1  3  4]]
[[ 3  8 -4  2]
 [-4 -1  0 -2]
 [ 1  0  1  0]
 [-3  9  7  1]]


In [17]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
# та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix16 = np.random.rand(3, 3)
print(matrix16)
print(np.sum(matrix16, axis=1))

[[0.72729033 0.21873761 0.71787039]
 [0.13072037 0.81618839 0.87937237]
 [0.77815616 0.79503875 0.80943404]]
[1.66389833 1.82628113 2.38262895]


In [18]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

matrix17 = np.random.randint(1, 11, size=(3, 4))
print(matrix17)
print(np.square(matrix17))

[[10  1  4  2]
 [ 6  6  8  1]
 [ 8  8 10  1]]
[[100   1  16   4]
 [ 36  36  64   1]
 [ 64  64 100   1]]


In [19]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
# та знайдіть вектор з квадратними коренями цих чисел.

vector18 = np.random.randint(1, 51, size=4)
print(vector18)
print(np.sqrt(vector18))

[35 19  5 46]
[5.91607978 4.35889894 2.23606798 6.78232998]
