In [2]:
import numpy as np

In [3]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

vector1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(vector1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

zeros = np.zeros((3, 3), dtype=int)
print(zeros)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

matrix3 = np.random.randint(1, 11, size=(5, 5))  
print(matrix3)

[[ 5 10  6  9  2]
 [ 9  5 10  1  8]
 [ 5  5  8  6  5]
 [ 1  5  9  8  5]
 [ 2  7  1  7  9]]


In [6]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

matrix4 = np.random.rand(4, 4)
print(matrix4)

[[0.16569343 0.54309346 0.77776337 0.21581317]
 [0.3624302  0.89181277 0.9223246  0.49111659]
 [0.46984127 0.66529093 0.46089667 0.77208015]
 [0.90927991 0.83147073 0.21083575 0.50438371]]


In [7]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
# та виконайте на них поелементні операції додавання, віднімання та множення.

vector5_1 = np.random.randint(1, 11, size=5)
vector5_2 = np.random.randint(1, 11, size=5)
print(vector5_1)
print(vector5_2)
print(vector5_1 + vector5_2)
print(vector5_1 - vector5_2)
print(vector5_1 * vector5_2)

[6 9 8 8 6]
[10  7 10  2  5]
[16 16 18 10 11]
[-4  2 -2  6  1]
[60 63 80 16 30]


In [8]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

vector6_1 = np.random.randint(1, 11, size=7)
vector6_2 = np.random.randint(1, 11, size=7)
print(vector6_1)
print(vector6_2)
print(np.dot(vector6_1, vector6_2))

[10  8 10  2  2  7 10]
[ 9  2  5 10  8  3  4]
253


In [9]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix7_1 = np.random.randint(1, 11, size=(2, 2)) 
matrix7_2 = np.random.randint(1, 11, size=(2, 3)) 
print(matrix7_1)
print(matrix7_2)
print(np.dot(matrix7_1, matrix7_2))

[[ 3  9]
 [10  6]]
[[10  6 10]
 [ 2  7  7]]
[[ 48  81  93]
 [112 102 142]]


In [10]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

matrix8 = np.random.randint(1, 11, size=(3, 3)) 
print(matrix8)
inv1 = np.linalg.inv(matrix8)
print(inv1)

[[ 2  7  7]
 [ 2  6  5]
 [ 2  3 10]]
[[-2.04545455  2.22727273  0.31818182]
 [ 0.45454545 -0.27272727 -0.18181818]
 [ 0.27272727 -0.36363636  0.09090909]]


In [11]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix9 = np.random.rand(4, 4)
print(matrix9)
inv2 = matrix9.T
print(inv2)

[[0.51468983 0.62380632 0.78239137 0.03472148]
 [0.06157996 0.43726546 0.32881624 0.5507673 ]
 [0.55150486 0.94681418 0.65038643 0.82176019]
 [0.18194399 0.98611851 0.43927288 0.1732478 ]]
[[0.51468983 0.06157996 0.55150486 0.18194399]
 [0.62380632 0.43726546 0.94681418 0.98611851]
 [0.78239137 0.32881624 0.65038643 0.43927288]
 [0.03472148 0.5507673  0.82176019 0.1732478 ]]


In [12]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами 
# в діапазоні від 1 до 10 та перемножте матрицю на вектор.

matrix10 = np.random.randint(1, 11, size=(3, 4)) 
vector10 = np.random.randint(1, 11, size=4)
print(matrix10)
print(vector10)
print(np.dot(matrix10, vector10))

[[3 9 2 3]
 [4 5 2 4]
 [9 9 5 9]]
[ 1  2  9 10]
[ 69  72 162]


In [13]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами 
# в діапазоні від 0 до 1 та перемножте матрицю на вектор.

matrix11 = np.random.rand(2, 3)
vector11 = np.random.rand(3)
print(matrix11)
print(vector11)
print(np.dot(matrix11, vector11))

[[0.56225493 0.01144101 0.85756616]
 [0.97846427 0.56367305 0.54105644]]
[0.01584309 0.76653911 0.20312516]
[0.1918711  0.55748151]


In [14]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 
# та виконайте їхнє поелементне множення.

matrix12_1 = np.random.randint(1, 11, size=(2, 2))
matrix12_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix12_1)
print(matrix12_2)
print(matrix12_1 * matrix12_2)

[[6 7]
 [9 3]]
[[1 6]
 [6 1]]
[[ 6 42]
 [54  3]]


In [15]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

matrix13_1 = np.random.randint(1, 11, size=(2, 2))
matrix13_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix13_1)
print(matrix13_2)
print(matrix13_1 + matrix13_2)

[[ 6 10]
 [ 9 10]]
[[3 5]
 [3 4]]
[[ 9 15]
 [12 14]]


In [16]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

matrix14 = np.random.randint(1, 101, size=(5, 5))
print(matrix14)
print(matrix14.sum())

[[100  12  99  42  74]
 [ 69  84  78  90   1]
 [ 23  74  76  33  67]
 [ 83  49  24  20  57]
 [ 47  30  37  41  25]]
1335


In [17]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

matrix15_1 = np.random.randint(1, 11, size=(4, 4))
matrix15_2 = np.random.randint(1, 11, size=(4, 4))
print(matrix15_1)
print(matrix15_2)
print(matrix15_1 - matrix15_2)

[[ 6  9  3  9]
 [ 5  7 10  1]
 [ 3  4  2  1]
 [ 4  8  4  9]]
[[ 8  9  2  2]
 [ 5  4  2 10]
 [ 6  3  6  4]
 [ 9  4  9  7]]
[[-2  0  1  7]
 [ 0  3  8 -9]
 [-3  1 -4 -3]
 [-5  4 -5  2]]


In [3]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 
# та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

matrix16 = np.random.rand(3, 3)
print(matrix16)
matrix16_1 = np.sum(matrix16, axis=1).reshape(-1,1)
print(matrix16_1)
print(matrix16_1.shape)

[[0.58205168 0.24083441 0.46208265]
 [0.32867121 0.80748284 0.66640202]
 [0.94144053 0.2205714  0.00365358]]
[[1.28496874]
 [1.80255607]
 [1.16566551]]
(3, 1)


In [19]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

matrix17 = np.random.randint(1, 11, size=(3, 4))
print(matrix17)
print(np.square(matrix17))

[[3 2 9 3]
 [7 8 8 7]
 [8 5 1 2]]
[[ 9  4 81  9]
 [49 64 64 49]
 [64 25  1  4]]


In [20]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 
# та знайдіть вектор з квадратними коренями цих чисел.

vector18 = np.random.randint(1, 51, size=4)
print(vector18)
print(np.sqrt(vector18))

[37 32 35 24]
[6.08276253 5.65685425 5.91607978 4.89897949]
